server:
  port: 18082
spring:
  application:
    name: tanhua-dubbo-mongo
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.10.2:8848
  data:
    mongodb:
      uri: mongodb://172.20.10.2:27017/tanhua
dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: spring-cloud://172.20.10.2
  scan:
    base-packages: com.study.api  #dubbo中包扫描